"""category

Revision ID: 04ac04a3813f
Revises: 35fbff672a32
Create Date: 2021-03-28 15:41:38.432760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ac04a3813f'
down_revision = '35fbff672a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'category')
    # ### end Alembic commands ###
