"""initial

Revision ID: 4033c1b4758a
Revises: 
Create Date: 2021-03-25 01:11:22.579122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4033c1b4758a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('serial', sa.String(length=50), nullable=True),
    sa.Column('wikilink', sa.String(length=250), nullable=True),
    sa.Column('thumbnail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thumbnail'], ['picture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_label'), 'item', ['label'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_label'), table_name='item')
    op.drop_table('item')
    op.drop_table('picture')
    # ### end Alembic commands ###
